services:
  uptimekuma:
    image: louislam/uptime-kuma:2
    container_name: Uptime-Kuma
    hostname: uptimekuma
    mem_limit: 4g
    cpu_shares: 1024
    ports:
      - 3444:3001
    volumes:
      - /volume1/docker/uptimekuma:/app/data:rw
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: America/Chicago
    restart: on-failure:5
